### ISSUE TITLE
OCP Registry

### ISSUE THREAD

**Issue by touma-I** [touma-I/sno#1]
Registry is set to managedState=Removed on startup

**Comment by touma-I** [comment]
Allocate space for disk on root device before creating PVC using local storage:

###export ocpnode=88-a4-c2-47-69-5e
```
export ocpnode=$(oc get node | sed -n 2p | awk '{print $1}')
```

```
oc debug nodes/$ocpnode -- chroot /host ls -l /mnt
oc debug nodes/$ocpnode -- chroot /host mkdir -p /mnt/disk/registry
oc debug nodes/$ocpnode -- chroot /host chmod 777 /mnt/disk/registry
oc debug nodes/$ocpnode -- chroot /host chcon -Rt svirt_sandbox_file_t /mnt/disk/registry
oc debug nodes/$ocpnode -- chroot /host ls -lZ /mnt/disk
```

**Comment by touma-I** [comment]
Create PV and PVC

```
cat <<EOF | oc create -f -
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: registry-storageclass
  local:
    path: /mnt/disk/registry
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - 88-a4-c2-47-69-5e

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-registry-storage-local
  namespace: openshift-image-registry
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: registry-storageclass
EOF

```
